var En = {
    'Menu' : 'Menu',
    'About' : 'About Us',
    'Contacts' : 'Contacts',
    'body_title' : 'Drinks that can brighten up any of your days',
    'now' : 'Now closed',
    //'closed' : 'closed',
    'open_hours' : 'Open every day 11 am - 10 pm',
    'button_NP' : 'New Products',
    'button_MT' : 'Milk Tea',
    'button_BD' : 'Branded Drinks',
    'button_S' : 'Smothies',
    'button_IT' : 'Ice Tea',
    'button_C' : 'Coffee',
    /*'large' : 'Large',
    'medium' : 'Medium',
    'bubbles' : 'Bubbles'*/
    'order' : 'Order through',
    'event' : '10th Boba tea for free',
    'event_des' : 'Come to Boba tea, collect nine marks on the coupon and get the tenth drink as a gift.',
    'AboutUs' : 'About Us',
    'about_us_text' : 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    'slogan' : "It's",
    'adress' : 'Türkistan, 16/5 Esil district, Nur-Sultan',
    'intst' : 'Opening hours',
    'op_hours' : 'Открытие'
};
var Ru = {
    'Menu' : 'Меню',
    'About' : 'О нас',
    'Contacts' : 'Контакты',
    'body_title' : 'Напитки которые скрасят любой из ваших дней',
    'now' : 'Сечайс закрыто',
    //'closed' : 'закрыто',
    'open_hours' : 'Открыт каждый день с 11 утра до 10 вечера',
    'button_NP' : 'Новиньки',
    'button_MT' : 'Чай с молоком',
    'button_BD' : 'Фирменные напитки',
    'button_S' : 'Смузи',
    'button_IT' : 'Холодный чай',
    'button_C' : 'Кофе',
    /*'large' : 'Большой',
    'medium' : 'Средний',
    'bubbles' : 'Пузырьки'*/
    'order' : 'Заказать через',
    'event' : '10-й чай Boba бесплатно',
    'event_des' : 'Приходите в Boba tea, соберите девять отметок на купоне и получите десятый напиток в подарок.',
    'AboutUs' : 'О Нас',
    'about_us_text' : 'какой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то тексткакой то текст какой то текст текст какой то текст текст какой то текст текст какой то текст текст какой то текст текст какой то текст текст какой то текст текст какой то текст',
    'slogan' : 'Это',
    'adress' : 'Түркістан, 16/5 Есиль район, Нур-Султан',
    'inst' : 'Подписывайтесь',
    'op_hours' : 'Открытие'
};